# Generated by Django 4.1.5 on 2023-01-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_farzi_coinname_rc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='farzi',
        ),
    ]
